import libraries

In [1]:
import pandas as pd
import requests
import json

In [2]:
from config import API_key

In [3]:
import config

ONE CITY

In [5]:
city = "Florence"
# country_code = "IT"
country_name = "Italy"
API_key = config.API_key
# limit = 1

weather_req = requests.get(f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric")
weather_json = weather_req.json()
weather_json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1680382800,
   'main': {'temp': 12.88,
    'feels_like': 12.08,
    'temp_min': 12.66,
    'temp_max': 12.88,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1000,
    'humidity': 71,
    'temp_kf': 0.22},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 36},
   'wind': {'speed': 1.17, 'deg': 132, 'gust': 1.46},
   'visibility': 10000,
   'pop': 0.09,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-01 21:00:00'},
  {'dt': 1680393600,
   'main': {'temp': 12.54,
    'feels_like': 11.73,
    'temp_min': 12.32,
    'temp_max': 12.54,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 999,
    'humidity': 72,
    'temp_kf': 0.22},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 54},
   'wind': {'speed': 0.79, 'deg': 138, 'gust': 1.25},
   'visibility': 10000,
   'pop': 0.25,
   'rain': {'3h': 0.19},
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-02 00:00:00'},
  {'dt': 1680404400,
   'main': {'temp': 10.54,
    'feels_like': 9.66,
    'temp_min': 10.54,
    'temp_max': 10.54,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 999,
    'humidity': 77,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 96},
   'wind': {'speed': 1.23, 'deg': 153, 'gust': 1.21},
   'visibility': 10000,
   'pop': 0.08,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-02 03:00:00'},
  {'dt': 1680415200,
   'main': {'temp': 10.93,
    'feels_like': 10.01,
    'temp_min': 10.93,
    'temp_max': 10.93,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1000,
    'humidity': 74,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 97},
   'wind': {'speed': 0.8, 'deg': 120, 'gust': 1},
   'visibility': 10000,
   'pop': 0.13,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-02 06:00:00'},
  {'dt': 1680426000,
   'main': {'temp': 15.61,
    'feels_like': 14.61,
    'temp_min': 15.61,
    'temp_max': 15.61,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1000,
    'humidity': 53,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 0.6, 'deg': 286, 'gust': 2.37},
   'visibility': 10000,
   'pop': 0.25,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-02 09:00:00'},
  {'dt': 1680436800,
   'main': {'temp': 18.21,
    'feels_like': 17.16,
    'temp_min': 18.21,
    'temp_max': 18.21,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1000,
    'humidity': 41,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 89},
   'wind': {'speed': 3.59, 'deg': 48, 'gust': 5.07},
   'visibility': 10000,
   'pop': 0.57,
   'rain': {'3h': 1.19},
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-02 12:00:00'},
  {'dt': 1680447600,
   'main': {'temp': 17.51,
    'feels_like': 16.44,
    'temp_min': 17.51,
    'temp_max': 17.51,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 1000,
    'humidity': 43,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.85, 'deg': 34, 'gust': 7.29},
   'visibility': 10000,
   'pop': 0.45,
   'rain': {'3h': 0.13},
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-02 15:00:00'},
  {'dt': 1680458400,
   'main': {'temp': 14.09,
    'feels_like': 13.2,
    'temp_min': 14.09,
    'temp_max': 14.09,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1001,
    'humidity': 63,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 96},
   'wind': {'speed': 3.69, 'deg': 27, 'gust': 8.17},
   'visibility': 10000,
   'pop': 0.41,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-02 18:00:00'},
  {'dt': 1680469200,
   'main': {'temp': 11.84,
    'feels_like': 11.04,
    'temp_min': 11.84,
    'temp_max': 11.84,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1003,
    'humidity': 75,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 89},
   'wind': {'speed': 2.61, 'deg': 26, 'gust': 6.02},
   'visibility': 10000,
   'pop': 0.05,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-02 21:00:00'},
  {'dt': 1680480000,
   'main': {'temp': 10.58,
    'feels_like': 9.7,
    'temp_min': 10.58,
    'temp_max': 10.58,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1003,
    'humidity': 77,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 92},
   'wind': {'speed': 2.38, 'deg': 27, 'gust': 8.13},
   'visibility': 10000,
   'pop': 0.01,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-03 00:00:00'},
  {'dt': 1680490800,
   'main': {'temp': 11.74,
    'feels_like': 10.85,
    'temp_min': 11.74,
    'temp_max': 11.74,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1003,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 82},
   'wind': {'speed': 5.05, 'deg': 24, 'gust': 10.53},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-03 03:00:00'},
  {'dt': 1680501600,
   'main': {'temp': 11.45,
    'feels_like': 10.17,
    'temp_min': 11.45,
    'temp_max': 11.45,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1003,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 56},
   'wind': {'speed': 4.93, 'deg': 36, 'gust': 11.61},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-03 06:00:00'},
  {'dt': 1680512400,
   'main': {'temp': 12.67,
    'feels_like': 11.35,
    'temp_min': 12.67,
    'temp_max': 12.67,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1004,
    'humidity': 52,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.74, 'deg': 33, 'gust': 11.27},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-03 09:00:00'},
  {'dt': 1680523200,
   'main': {'temp': 14.25,
    'feels_like': 12.64,
    'temp_min': 14.25,
    'temp_max': 14.25,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1004,
    'humidity': 35,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 61},
   'wind': {'speed': 6.93, 'deg': 31, 'gust': 12.36},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-03 12:00:00'},
  {'dt': 1680534000,
   'main': {'temp': 13.99,
    'feels_like': 12.46,
    'temp_min': 13.99,
    'temp_max': 13.99,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1003,
    'humidity': 39,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 6},
   'wind': {'speed': 7.03, 'deg': 40, 'gust': 13.39},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-03 15:00:00'},
  {'dt': 1680544800,
   'main': {'temp': 10.1,
    'feels_like': 8.47,
    'temp_min': 10.1,
    'temp_max': 10.1,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1004,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 3},
   'wind': {'speed': 6.52, 'deg': 43, 'gust': 15.2},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-03 18:00:00'},
  {'dt': 1680555600,
   'main': {'temp': 8.21,
    'feels_like': 4.65,
    'temp_min': 8.21,
    'temp_max': 8.21,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1006,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 6.97, 'deg': 47, 'gust': 15.99},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-03 21:00:00'},
  {'dt': 1680566400,
   'main': {'temp': 7.19,
    'feels_like': 4.16,
    'temp_min': 7.19,
    'temp_max': 7.19,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1006,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 4.8, 'deg': 39, 'gust': 14.4},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-04 00:00:00'},
  {'dt': 1680577200,
   'main': {'temp': 6.34,
    'feels_like': 3.09,
    'temp_min': 6.34,
    'temp_max': 6.34,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1006,
    'humidity': 46,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 4.82, 'deg': 35, 'gust': 13.39},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-04 03:00:00'},
  {'dt': 1680588000,
   'main': {'temp': 6.27,
    'feels_like': 3.08,
    'temp_min': 6.27,
    'temp_max': 6.27,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1007,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 10},
   'wind': {'speed': 4.66, 'deg': 35, 'gust': 12.1},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-04 06:00:00'},
  {'dt': 1680598800,
   'main': {'temp': 9.69,
    'feels_like': 6.56,
    'temp_min': 9.69,
    'temp_max': 9.69,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1008,
    'humidity': 32,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 7},
   'wind': {'speed': 6.93, 'deg': 47, 'gust': 11.54},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-04 09:00:00'},
  {'dt': 1680609600,
   'main': {'temp': 12.06,
    'feels_like': 9.97,
    'temp_min': 12.06,
    'temp_max': 12.06,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1007,
    'humidity': 25,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 21},
   'wind': {'speed': 7.06, 'deg': 46, 'gust': 10.2},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-04 12:00:00'},
  {'dt': 1680620400,
   'main': {'temp': 11.3,
    'feels_like': 9.3,
    'temp_min': 11.3,
    'temp_max': 11.3,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1007,
    'humidity': 31,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 14},
   'wind': {'speed': 6.81, 'deg': 44, 'gust': 10},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-04 15:00:00'},
  {'dt': 1680631200,
   'main': {'temp': 8.3,
    'feels_like': 5.86,
    'temp_min': 8.3,
    'temp_max': 8.3,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1009,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 9},
   'wind': {'speed': 4.1, 'deg': 32, 'gust': 9.69},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-04 18:00:00'},
  {'dt': 1680642000,
   'main': {'temp': 7.35,
    'feels_like': 4.8,
    'temp_min': 7.35,
    'temp_max': 7.35,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1010,
    'humidity': 51,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 3.9, 'deg': 31, 'gust': 11.18},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-04 21:00:00'},
  {'dt': 1680652800,
   'main': {'temp': 6.64,
    'feels_like': 3.64,
    'temp_min': 6.64,
    'temp_max': 6.64,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1010,
    'humidity': 55,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 4.45, 'deg': 28, 'gust': 11.16},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-05 00:00:00'},
  {'dt': 1680663600,
   'main': {'temp': 6,
    'feels_like': 3.4,
    'temp_min': 6,
    'temp_max': 6,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1010,
    'humidity': 56,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 3.46, 'deg': 26, 'gust': 9.53},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-05 03:00:00'},
  {'dt': 1680674400,
   'main': {'temp': 5.87,
    'feels_like': 3.81,
    'temp_min': 5.87,
    'temp_max': 5.87,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1011,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 4},
   'wind': {'speed': 2.65, 'deg': 24, 'gust': 7.9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-05 06:00:00'},
  {'dt': 1680685200,
   'main': {'temp': 10.72,
    'feels_like': 8.81,
    'temp_min': 10.72,
    'temp_max': 10.72,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1011,
    'humidity': 37,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 2},
   'wind': {'speed': 4.63, 'deg': 38, 'gust': 6.34},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-05 09:00:00'},
  {'dt': 1680696000,
   'main': {'temp': 13.06,
    'feels_like': 11.23,
    'temp_min': 13.06,
    'temp_max': 13.06,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1011,
    'humidity': 31,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 7},
   'wind': {'speed': 4.89, 'deg': 42, 'gust': 5.31},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-05 12:00:00'},
  {'dt': 1680706800,
   'main': {'temp': 12.41,
    'feels_like': 10.49,
    'temp_min': 12.41,
    'temp_max': 12.41,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1011,
    'humidity': 30,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 9},
   'wind': {'speed': 5.47, 'deg': 44, 'gust': 6.18},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-05 15:00:00'},
  {'dt': 1680717600,
   'main': {'temp': 8.82,
    'feels_like': 6.59,
    'temp_min': 8.82,
    'temp_max': 8.82,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1012,
    'humidity': 38,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 5},
   'wind': {'speed': 3.93, 'deg': 29, 'gust': 7.73},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-05 18:00:00'},
  {'dt': 1680728400,
   'main': {'temp': 6.5,
    'feels_like': 4.83,
    'temp_min': 6.5,
    'temp_max': 6.5,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1014,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 2.31, 'deg': 40, 'gust': 5.64},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-05 21:00:00'},
  {'dt': 1680739200,
   'main': {'temp': 5.3,
    'feels_like': 3.32,
    'temp_min': 5.3,
    'temp_max': 5.3,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1014,
    'humidity': 56,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 20},
   'wind': {'speed': 2.43, 'deg': 34, 'gust': 7.01},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-06 00:00:00'},
  {'dt': 1680750000,
   'main': {'temp': 5.53,
    'feels_like': 2.69,
    'temp_min': 5.53,
    'temp_max': 5.53,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1013,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.69, 'deg': 31, 'gust': 10.51},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2023-04-06 03:00:00'},
  {'dt': 1680760800,
   'main': {'temp': 6.03,
    'feels_like': 3.59,
    'temp_min': 6.03,
    'temp_max': 6.03,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1012,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.22, 'deg': 31, 'gust': 9.86},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-06 06:00:00'},
  {'dt': 1680771600,
   'main': {'temp': 11.15,
    'feels_like': 9.23,
    'temp_min': 11.15,
    'temp_max': 11.15,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1011,
    'humidity': 35,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 98},
   'wind': {'speed': 6.9, 'deg': 34, 'gust': 10.51},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-06 09:00:00'},
  {'dt': 1680782400,
   'main': {'temp': 13.42,
    'feels_like': 11.6,
    'temp_min': 13.42,
    'temp_max': 13.42,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1010,
    'humidity': 30,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 80},
   'wind': {'speed': 7.11, 'deg': 45, 'gust': 9.92},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-06 12:00:00'},
  {'dt': 1680793200,
   'main': {'temp': 12.51,
    'feels_like': 10.7,
    'temp_min': 12.51,
    'temp_max': 12.51,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1008,
    'humidity': 34,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 62},
   'wind': {'speed': 6.84, 'deg': 43, 'gust': 9.96},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2023-04-06 15:00:00'},
  {'dt': 1680804000,

In [52]:
#json keys
weather_json['city']

{'id': 3176959,
 'name': 'Florence',
 'coord': {'lat': 43.7667, 'lon': 11.25},
 'country': 'IT',
 'population': 371517,
 'timezone': 7200,
 'sunrise': 1680325036,
 'sunset': 1680370825}

In [7]:
weather_json['city']

{'id': 3176959,
 'name': 'Florence',
 'coord': {'lat': 43.7667, 'lon': 11.25},
 'country': 'IT',
 'population': 371517,
 'timezone': 7200,
 'sunrise': 1680325036,
 'sunset': 1680370825}

In [8]:
# city values
weather_json['city']['coord']['lat']

43.7667

In [9]:
weather_json['city']['coord']['lon']

11.25

In [10]:
#access to the list of weather
weather_json['list'][0]['weather']

[{'id': 802,
  'main': 'Clouds',
  'description': 'scattered clouds',
  'icon': '03n'}]

In [11]:
#access wind info
weather_json['list'][0]['wind']['speed']

1.17

In [12]:
weather_json['list'][0]['main']['feels_like']

12.08

In [13]:
weather_json['city']

{'id': 3176959,
 'name': 'Florence',
 'coord': {'lat': 43.7667, 'lon': 11.25},
 'country': 'IT',
 'population': 371517,
 'timezone': 7200,
 'sunrise': 1680325036,
 'sunset': 1680370825}

In [14]:
#access rain info
weather_json['list']

[{'dt': 1680382800,
  'main': {'temp': 12.88,
   'feels_like': 12.08,
   'temp_min': 12.66,
   'temp_max': 12.88,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1000,
   'humidity': 71,
   'temp_kf': 0.22},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 36},
  'wind': {'speed': 1.17, 'deg': 132, 'gust': 1.46},
  'visibility': 10000,
  'pop': 0.09,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-01 21:00:00'},
 {'dt': 1680393600,
  'main': {'temp': 12.54,
   'feels_like': 11.73,
   'temp_min': 12.32,
   'temp_max': 12.54,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 999,
   'humidity': 72,
   'temp_kf': 0.22},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 54},
  'wind': {'speed': 0.79, 'deg': 138, 'gust': 1.25},
  'visibility': 10000,
  'pop': 0.25,
  'rain': {'3h': 0.19},
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-02 00:00:00'},
 {'dt': 1680404400,
  'main': {'temp': 10.54,
   'feels_like': 9.66,
   'temp_min': 10.54,
   'temp_max': 10.54,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 999,
   'humidity': 77,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 96},
  'wind': {'speed': 1.23, 'deg': 153, 'gust': 1.21},
  'visibility': 10000,
  'pop': 0.08,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-02 03:00:00'},
 {'dt': 1680415200,
  'main': {'temp': 10.93,
   'feels_like': 10.01,
   'temp_min': 10.93,
   'temp_max': 10.93,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 1000,
   'humidity': 74,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 97},
  'wind': {'speed': 0.8, 'deg': 120, 'gust': 1},
  'visibility': 10000,
  'pop': 0.13,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-02 06:00:00'},
 {'dt': 1680426000,
  'main': {'temp': 15.61,
   'feels_like': 14.61,
   'temp_min': 15.61,
   'temp_max': 15.61,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1000,
   'humidity': 53,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 0.6, 'deg': 286, 'gust': 2.37},
  'visibility': 10000,
  'pop': 0.25,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-02 09:00:00'},
 {'dt': 1680436800,
  'main': {'temp': 18.21,
   'feels_like': 17.16,
   'temp_min': 18.21,
   'temp_max': 18.21,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 1000,
   'humidity': 41,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 89},
  'wind': {'speed': 3.59, 'deg': 48, 'gust': 5.07},
  'visibility': 10000,
  'pop': 0.57,
  'rain': {'3h': 1.19},
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-02 12:00:00'},
 {'dt': 1680447600,
  'main': {'temp': 17.51,
   'feels_like': 16.44,
   'temp_min': 17.51,
   'temp_max': 17.51,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 1000,
   'humidity': 43,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.85, 'deg': 34, 'gust': 7.29},
  'visibility': 10000,
  'pop': 0.45,
  'rain': {'3h': 0.13},
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-02 15:00:00'},
 {'dt': 1680458400,
  'main': {'temp': 14.09,
   'feels_like': 13.2,
   'temp_min': 14.09,
   'temp_max': 14.09,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 1001,
   'humidity': 63,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 96},
  'wind': {'speed': 3.69, 'deg': 27, 'gust': 8.17},
  'visibility': 10000,
  'pop': 0.41,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-02 18:00:00'},
 {'dt': 1680469200,
  'main': {'temp': 11.84,
   'feels_like': 11.04,
   'temp_min': 11.84,
   'temp_max': 11.84,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1003,
   'humidity': 75,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 89},
  'wind': {'speed': 2.61, 'deg': 26, 'gust': 6.02},
  'visibility': 10000,
  'pop': 0.05,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-02 21:00:00'},
 {'dt': 1680480000,
  'main': {'temp': 10.58,
   'feels_like': 9.7,
   'temp_min': 10.58,
   'temp_max': 10.58,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1003,
   'humidity': 77,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 92},
  'wind': {'speed': 2.38, 'deg': 27, 'gust': 8.13},
  'visibility': 10000,
  'pop': 0.01,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-03 00:00:00'},
 {'dt': 1680490800,
  'main': {'temp': 11.74,
   'feels_like': 10.85,
   'temp_min': 11.74,
   'temp_max': 11.74,
   'pressure': 1010,
   'sea_level': 1010,
   'grnd_level': 1003,
   'humidity': 72,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 82},
  'wind': {'speed': 5.05, 'deg': 24, 'gust': 10.53},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-03 03:00:00'},
 {'dt': 1680501600,
  'main': {'temp': 11.45,
   'feels_like': 10.17,
   'temp_min': 11.45,
   'temp_max': 11.45,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1003,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 56},
  'wind': {'speed': 4.93, 'deg': 36, 'gust': 11.61},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-03 06:00:00'},
 {'dt': 1680512400,
  'main': {'temp': 12.67,
   'feels_like': 11.35,
   'temp_min': 12.67,
   'temp_max': 12.67,
   'pressure': 1012,
   'sea_level': 1012,
   'grnd_level': 1004,
   'humidity': 52,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.74, 'deg': 33, 'gust': 11.27},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-03 09:00:00'},
 {'dt': 1680523200,
  'main': {'temp': 14.25,
   'feels_like': 12.64,
   'temp_min': 14.25,
   'temp_max': 14.25,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1004,
   'humidity': 35,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 61},
  'wind': {'speed': 6.93, 'deg': 31, 'gust': 12.36},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-03 12:00:00'},
 {'dt': 1680534000,
  'main': {'temp': 13.99,
   'feels_like': 12.46,
   'temp_min': 13.99,
   'temp_max': 13.99,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1003,
   'humidity': 39,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 7.03, 'deg': 40, 'gust': 13.39},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-03 15:00:00'},
 {'dt': 1680544800,
  'main': {'temp': 10.1,
   'feels_like': 8.47,
   'temp_min': 10.1,
   'temp_max': 10.1,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 1004,
   'humidity': 50,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 3},
  'wind': {'speed': 6.52, 'deg': 43, 'gust': 15.2},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-03 18:00:00'},
 {'dt': 1680555600,
  'main': {'temp': 8.21,
   'feels_like': 4.65,
   'temp_min': 8.21,
   'temp_max': 8.21,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1006,
   'humidity': 49,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 1},
  'wind': {'speed': 6.97, 'deg': 47, 'gust': 15.99},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-03 21:00:00'},
 {'dt': 1680566400,
  'main': {'temp': 7.19,
   'feels_like': 4.16,
   'temp_min': 7.19,
   'temp_max': 7.19,
   'pressure': 1013,
   'sea_level': 1013,
   'grnd_level': 1006,
   'humidity': 49,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 1},
  'wind': {'speed': 4.8, 'deg': 39, 'gust': 14.4},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-04 00:00:00'},
 {'dt': 1680577200,
  'main': {'temp': 6.34,
   'feels_like': 3.09,
   'temp_min': 6.34,
   'temp_max': 6.34,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 1006,
   'humidity': 46,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 0},
  'wind': {'speed': 4.82, 'deg': 35, 'gust': 13.39},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-04 03:00:00'},
 {'dt': 1680588000,
  'main': {'temp': 6.27,
   'feels_like': 3.08,
   'temp_min': 6.27,
   'temp_max': 6.27,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1007,
   'humidity': 45,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 10},
  'wind': {'speed': 4.66, 'deg': 35, 'gust': 12.1},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-04 06:00:00'},
 {'dt': 1680598800,
  'main': {'temp': 9.69,
   'feels_like': 6.56,
   'temp_min': 9.69,
   'temp_max': 9.69,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1008,
   'humidity': 32,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 7},
  'wind': {'speed': 6.93, 'deg': 47, 'gust': 11.54},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-04 09:00:00'},
 {'dt': 1680609600,
  'main': {'temp': 12.06,
   'feels_like': 9.97,
   'temp_min': 12.06,
   'temp_max': 12.06,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1007,
   'humidity': 25,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 21},
  'wind': {'speed': 7.06, 'deg': 46, 'gust': 10.2},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-04 12:00:00'},
 {'dt': 1680620400,
  'main': {'temp': 11.3,
   'feels_like': 9.3,
   'temp_min': 11.3,
   'temp_max': 11.3,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 1007,
   'humidity': 31,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 14},
  'wind': {'speed': 6.81, 'deg': 44, 'gust': 10},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-04 15:00:00'},
 {'dt': 1680631200,
  'main': {'temp': 8.3,
   'feels_like': 5.86,
   'temp_min': 8.3,
   'temp_max': 8.3,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1009,
   'humidity': 45,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 9},
  'wind': {'speed': 4.1, 'deg': 32, 'gust': 9.69},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-04 18:00:00'},
 {'dt': 1680642000,
  'main': {'temp': 7.35,
   'feels_like': 4.8,
   'temp_min': 7.35,
   'temp_max': 7.35,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1010,
   'humidity': 51,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 2},
  'wind': {'speed': 3.9, 'deg': 31, 'gust': 11.18},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-04 21:00:00'},
 {'dt': 1680652800,
  'main': {'temp': 6.64,
   'feels_like': 3.64,
   'temp_min': 6.64,
   'temp_max': 6.64,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1010,
   'humidity': 55,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 1},
  'wind': {'speed': 4.45, 'deg': 28, 'gust': 11.16},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-05 00:00:00'},
 {'dt': 1680663600,
  'main': {'temp': 6,
   'feels_like': 3.4,
   'temp_min': 6,
   'temp_max': 6,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 1010,
   'humidity': 56,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 2},
  'wind': {'speed': 3.46, 'deg': 26, 'gust': 9.53},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-05 03:00:00'},
 {'dt': 1680674400,
  'main': {'temp': 5.87,
   'feels_like': 3.81,
   'temp_min': 5.87,
   'temp_max': 5.87,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1011,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 4},
  'wind': {'speed': 2.65, 'deg': 24, 'gust': 7.9},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-05 06:00:00'},
 {'dt': 1680685200,
  'main': {'temp': 10.72,
   'feels_like': 8.81,
   'temp_min': 10.72,
   'temp_max': 10.72,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1011,
   'humidity': 37,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 2},
  'wind': {'speed': 4.63, 'deg': 38, 'gust': 6.34},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-05 09:00:00'},
 {'dt': 1680696000,
  'main': {'temp': 13.06,
   'feels_like': 11.23,
   'temp_min': 13.06,
   'temp_max': 13.06,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1011,
   'humidity': 31,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 7},
  'wind': {'speed': 4.89, 'deg': 42, 'gust': 5.31},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-05 12:00:00'},
 {'dt': 1680706800,
  'main': {'temp': 12.41,
   'feels_like': 10.49,
   'temp_min': 12.41,
   'temp_max': 12.41,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1011,
   'humidity': 30,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 9},
  'wind': {'speed': 5.47, 'deg': 44, 'gust': 6.18},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-05 15:00:00'},
 {'dt': 1680717600,
  'main': {'temp': 8.82,
   'feels_like': 6.59,
   'temp_min': 8.82,
   'temp_max': 8.82,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1012,
   'humidity': 38,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 5},
  'wind': {'speed': 3.93, 'deg': 29, 'gust': 7.73},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-05 18:00:00'},
 {'dt': 1680728400,
  'main': {'temp': 6.5,
   'feels_like': 4.83,
   'temp_min': 6.5,
   'temp_max': 6.5,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1014,
   'humidity': 49,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 2},
  'wind': {'speed': 2.31, 'deg': 40, 'gust': 5.64},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-05 21:00:00'},
 {'dt': 1680739200,
  'main': {'temp': 5.3,
   'feels_like': 3.32,
   'temp_min': 5.3,
   'temp_max': 5.3,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1014,
   'humidity': 56,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 20},
  'wind': {'speed': 2.43, 'deg': 34, 'gust': 7.01},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-06 00:00:00'},
 {'dt': 1680750000,
  'main': {'temp': 5.53,
   'feels_like': 2.69,
   'temp_min': 5.53,
   'temp_max': 5.53,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1013,
   'humidity': 59,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.69, 'deg': 31, 'gust': 10.51},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-06 03:00:00'},
 {'dt': 1680760800,
  'main': {'temp': 6.03,
   'feels_like': 3.59,
   'temp_min': 6.03,
   'temp_max': 6.03,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 1012,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.22, 'deg': 31, 'gust': 9.86},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-06 06:00:00'},
 {'dt': 1680771600,
  'main': {'temp': 11.15,
   'feels_like': 9.23,
   'temp_min': 11.15,
   'temp_max': 11.15,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 1011,
   'humidity': 35,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 98},
  'wind': {'speed': 6.9, 'deg': 34, 'gust': 10.51},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-06 09:00:00'},
 {'dt': 1680782400,
  'main': {'temp': 13.42,
   'feels_like': 11.6,
   'temp_min': 13.42,
   'temp_max': 13.42,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 1010,
   'humidity': 30,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 80},
  'wind': {'speed': 7.11, 'deg': 45, 'gust': 9.92},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-06 12:00:00'},
 {'dt': 1680793200,
  'main': {'temp': 12.51,
   'feels_like': 10.7,
   'temp_min': 12.51,
   'temp_max': 12.51,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1008,
   'humidity': 34,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 62},
  'wind': {'speed': 6.84, 'deg': 43, 'gust': 9.96},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2023-04-06 15:00:00'},
 {'dt': 1680804000,
  'main': {'temp': 9.04,
   'feels_like': 6.35,
   'temp_min': 9.04,
   'temp_max': 9.04,
   'pressure': 1016,
   'sea_level': 1016,
   'grnd_level': 1008,
   'humidity': 55,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 33},
  'wind': {'speed': 5.09, 'deg': 25, 'gust': 10.62},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2023-04-06 18:00:00'}]

In [15]:
weather_json['list'][0]

{'dt': 1680382800,
 'main': {'temp': 12.88,
  'feels_like': 12.08,
  'temp_min': 12.66,
  'temp_max': 12.88,
  'pressure': 1008,
  'sea_level': 1008,
  'grnd_level': 1000,
  'humidity': 71,
  'temp_kf': 0.22},
 'weather': [{'id': 802,
   'main': 'Clouds',
   'description': 'scattered clouds',
   'icon': '03n'}],
 'clouds': {'all': 36},
 'wind': {'speed': 1.17, 'deg': 132, 'gust': 1.46},
 'visibility': 10000,
 'pop': 0.09,
 'sys': {'pod': 'n'},
 'dt_txt': '2023-04-01 21:00:00'}

In [16]:
len(weather_json['city'])

8

In [17]:
weather_dict = {
    'city': [],
    'country_code': [],
    'lat': [],
    'lon': [],
    'temp': [],
    'time': []
}


for i in range(len(weather_json["list"])):
    weather_dict['city'].append(weather_json['city']['name'])
    weather_dict['country_code'].append(weather_json['city']['country'])
    weather_dict['lat'].append(weather_json['city']['coord']['lat'])
    weather_dict['lon'].append(weather_json['city']['coord']['lon'])
    weather_dict['temp'].append(weather_json['list'][i]['main']['temp'])
    weather_dict['time'].append(weather_json['list'][i]['dt_txt'])

In [18]:
weather_df = pd.DataFrame(weather_dict)
weather_df

        city country_code      lat    lon   temp                 time
0   Florence           IT  43.7667  11.25  12.88  2023-04-01 21:00:00
1   Florence           IT  43.7667  11.25  12.54  2023-04-02 00:00:00
2   Florence           IT  43.7667  11.25  10.54  2023-04-02 03:00:00
3   Florence           IT  43.7667  11.25  10.93  2023-04-02 06:00:00
4   Florence           IT  43.7667  11.25  15.61  2023-04-02 09:00:00
5   Florence           IT  43.7667  11.25  18.21  2023-04-02 12:00:00
6   Florence           IT  43.7667  11.25  17.51  2023-04-02 15:00:00
7   Florence           IT  43.7667  11.25  14.09  2023-04-02 18:00:00
8   Florence           IT  43.7667  11.25  11.84  2023-04-02 21:00:00
9   Florence           IT  43.7667  11.25  10.58  2023-04-03 00:00:00
10  Florence           IT  43.7667  11.25  11.74  2023-04-03 03:00:00
11  Florence           IT  43.7667  11.25  11.45  2023-04-03 06:00:00
12  Florence           IT  43.7667  11.25  12.67  2023-04-03 09:00:00
13  Florence           IT  43.7667  11.25  14.25  2023-04-03 12:00:00
14  Florence           IT  43.7667  11.25  13.99  2023-04-03 15:00:00
15  Florence           IT  43.7667  11.25  10.10  2023-04-03 18:00:00
16  Florence           IT  43.7667  11.25   8.21  2023-04-03 21:00:00
17  Florence           IT  43.7667  11.25   7.19  2023-04-04 00:00:00
18  Florence           IT  43.7667  11.25   6.34  2023-04-04 03:00:00
19  Florence           IT  43.7667  11.25   6.27  2023-04-04 06:00:00
20  Florence           IT  43.7667  11.25   9.69  2023-04-04 09:00:00
21  Florence           IT  43.7667  11.25  12.06  2023-04-04 12:00:00
22  Florence           IT  43.7667  11.25  11.30  2023-04-04 15:00:00
23  Florence           IT  43.7667  11.25   8.30  2023-04-04 18:00:00
24  Florence           IT  43.7667  11.25   7.35  2023-04-04 21:00:00
25  Florence           IT  43.7667  11.25   6.64  2023-04-05 00:00:00
26  Florence           IT  43.7667  11.25   6.00  2023-04-05 03:00:00
27  Florence           IT  43.7667  11.25   5.87  2023-04-05 06:00:00
28  Florence           IT  43.7667  11.25  10.72  2023-04-05 09:00:00
29  Florence           IT  43.7667  11.25  13.06  2023-04-05 12:00:00
30  Florence           IT  43.7667  11.25  12.41  2023-04-05 15:00:00
31  Florence           IT  43.7667  11.25   8.82  2023-04-05 18:00:00
32  Florence           IT  43.7667  11.25   6.50  2023-04-05 21:00:00
33  Florence           IT  43.7667  11.25   5.30  2023-04-06 00:00:00
34  Florence           IT  43.7667  11.25   5.53  2023-04-06 03:00:00
35  Florence           IT  43.7667  11.25   6.03  2023-04-06 06:00:00
36  Florence           IT  43.7667  11.25  11.15  2023-04-06 09:00:00
37  Florence           IT  43.7667  11.25  13.42  2023-04-06 12:00:00
38  Florence           IT  43.7667  11.25  12.51  2023-04-06 15:00:00
39  Florence           IT  43.7667  11.25   9.04  2023-04-06 18:00:00

In [19]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          40 non-null     object
 1   country_code  40 non-null     object
 2   lat           40 non-null     float64
 3   lon           40 non-null     float64
 4   temp          40 non-null     float64
 5   time          40 non-null     object
dtypes: float64(3), object(3)
memory usage: 2.0+ KB

In [20]:
#convert time to datetime
weather_df['time'] = pd.to_datetime(weather_df['time'])
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          40 non-null     object
 1   country_code  40 non-null     object
 2   lat           40 non-null     float64
 3   lon           40 non-null     float64
 4   temp          40 non-null     float64
 5   time          40 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 2.0+ KB

In [21]:
weather_df.head()

       city country_code      lat    lon   temp                time
0  Florence           IT  43.7667  11.25  12.88 2023-04-01 21:00:00
1  Florence           IT  43.7667  11.25  12.54 2023-04-02 00:00:00
2  Florence           IT  43.7667  11.25  10.54 2023-04-02 03:00:00
3  Florence           IT  43.7667  11.25  10.93 2023-04-02 06:00:00
4  Florence           IT  43.7667  11.25  15.61 2023-04-02 09:00:00

FORECAST DATAFRAME

In [22]:
#Forecast dictionary 
forecast_dict = {
    'forecast_time': [],
    'outlook': [],
    'temp': [],
    'feels_like': [],
    'wind_speed': [],
    'humidity': []
}


for i in range(len(weather_json["list"])):
    forecast_dict['feels_like'].append(weather_json['list'][i]['main']['feels_like'])
    forecast_dict['outlook'].append(weather_json['list'][i]['weather'][0]['description'])
    forecast_dict['wind_speed'].append(weather_json['list'][i]['wind']['speed'])
    forecast_dict['humidity'].append(weather_json['list'][i]['main']['humidity'])
    forecast_dict['temp'].append(weather_json['list'][i]['main']['temp'])
    forecast_dict['forecast_time'].append(weather_json['list'][i]['dt_txt'])

In [23]:
forecast_dict

{'forecast_time': ['2023-04-01 21:00:00',
  '2023-04-02 00:00:00',
  '2023-04-02 03:00:00',
  '2023-04-02 06:00:00',
  '2023-04-02 09:00:00',
  '2023-04-02 12:00:00',
  '2023-04-02 15:00:00',
  '2023-04-02 18:00:00',
  '2023-04-02 21:00:00',
  '2023-04-03 00:00:00',
  '2023-04-03 03:00:00',
  '2023-04-03 06:00:00',
  '2023-04-03 09:00:00',
  '2023-04-03 12:00:00',
  '2023-04-03 15:00:00',
  '2023-04-03 18:00:00',
  '2023-04-03 21:00:00',
  '2023-04-04 00:00:00',
  '2023-04-04 03:00:00',
  '2023-04-04 06:00:00',
  '2023-04-04 09:00:00',
  '2023-04-04 12:00:00',
  '2023-04-04 15:00:00',
  '2023-04-04 18:00:00',
  '2023-04-04 21:00:00',
  '2023-04-05 00:00:00',
  '2023-04-05 03:00:00',
  '2023-04-05 06:00:00',
  '2023-04-05 09:00:00',
  '2023-04-05 12:00:00',
  '2023-04-05 15:00:00',
  '2023-04-05 18:00:00',
  '2023-04-05 21:00:00',
  '2023-04-06 00:00:00',
  '2023-04-06 03:00:00',
  '2023-04-06 06:00:00',
  '2023-04-06 09:00:00',
  '2023-04-06 12:00:00',
  '2023-04-06 15:00:00',
  '2023-04-06 18:00:00'],
 'outlook': ['scattered clouds',
  'light rain',
  'overcast clouds',
  'overcast clouds',
  'overcast clouds',
  'light rain',
  'light rain',
  'overcast clouds',
  'overcast clouds',
  'overcast clouds',
  'broken clouds',
  'broken clouds',
  'overcast clouds',
  'broken clouds',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'few clouds',
  'few clouds',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'clear sky',
  'few clouds',
  'overcast clouds',
  'overcast clouds',
  'overcast clouds',
  'broken clouds',
  'broken clouds',
  'scattered clouds'],
 'temp': [12.88,
  12.54,
  10.54,
  10.93,
  15.61,
  18.21,
  17.51,
  14.09,
  11.84,
  10.58,
  11.74,
  11.45,
  12.67,
  14.25,
  13.99,
  10.1,
  8.21,
  7.19,
  6.34,
  6.27,
  9.69,
  12.06,
  11.3,
  8.3,
  7.35,
  6.64,
  6,
  5.87,
  10.72,
  13.06,
  12.41,
  8.82,
  6.5,
  5.3,
  5.53,
  6.03,
  11.15,
  13.42,
  12.51,
  9.04],
 'feels_like': [12.08,
  11.73,
  9.66,
  10.01,
  14.61,
  17.16,
  16.44,
  13.2,
  11.04,
  9.7,
  10.85,
  10.17,
  11.35,
  12.64,
  12.46,
  8.47,
  4.65,
  4.16,
  3.09,
  3.08,
  6.56,
  9.97,
  9.3,
  5.86,
  4.8,
  3.64,
  3.4,
  3.81,
  8.81,
  11.23,
  10.49,
  6.59,
  4.83,
  3.32,
  2.69,
  3.59,
  9.23,
  11.6,
  10.7,
  6.35],
 'wind_speed': [1.17,
  0.79,
  1.23,
  0.8,
  0.6,
  3.59,
  5.85,
  3.69,
  2.61,
  2.38,
  5.05,
  4.93,
  5.74,
  6.93,
  7.03,
  6.52,
  6.97,
  4.8,
  4.82,
  4.66,
  6.93,
  7.06,
  6.81,
  4.1,
  3.9,
  4.45,
  3.46,
  2.65,
  4.63,
  4.89,
  5.47,
  3.93,
  2.31,
  2.43,
  3.69,
  3.22,
  6.9,
  7.11,
  6.84,
  5.09],
 'humidity': [71,
  72,
  77,
  74,
  53,
  41,
  43,
  63,
  75,
  77,
  72,
  58,
  52,
  35,
  39,
  50,
  49,
  49,
  46,
  45,
  32,
  25,
  31,
  45,
  51,
  55,
  56,
  58,
  37,
  31,
  30,
  38,
  49,
  56,
  59,
  58,
  35,
  30,
  34,
  55]}

In [24]:
#CREATE FORECAST DF from dictionary
forecast_df = pd.DataFrame(forecast_dict)
forecast_df.head()

,forecast_time,outlook,temp,feels_like,wind_speed,humidity
0,2023-04-01 21:00:00,scattered clouds,12.88,12.08,1.17,71
1,2023-04-02 00:00:00,light rain,12.54,11.73,0.79,72
2,2023-04-02 03:00:00,overcast clouds,10.54,9.66,1.23,77
3,2023-04-02 06:00:00,overcast clouds,10.93,10.01,0.80,74
4,2023-04-02 09:00:00,overcast clouds,15.61,14.61,0.60,53

In [25]:
forecast_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   forecast_time  40 non-null     object
 1   outlook        40 non-null     object
 2   temp           40 non-null     float64
 3   feels_like     40 non-null     float64
 4   wind_speed     40 non-null     float64
 5   humidity       40 non-null     int64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.0+ KB

In [26]:
#convert forecast_time column to datetime
forecast_df['forecast_time'] = pd.to_datetime(forecast_df['forecast_time'])
forecast_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   forecast_time  40 non-null     datetime64[ns]
 1   outlook        40 non-null     object
 2   temp           40 non-null     float64
 3   feels_like     40 non-null     float64
 4   wind_speed     40 non-null     float64
 5   humidity       40 non-null     int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 2.0+ KB

In [51]:
forecast_df

,forecast_time,outlook,temp,feels_like,wind_speed,humidity
0,2023-04-01 21:00:00,scattered clouds,12.88,12.08,1.17,71
1,2023-04-02 00:00:00,light rain,12.54,11.73,0.79,72
2,2023-04-02 03:00:00,overcast clouds,10.54,9.66,1.23,77
3,2023-04-02 06:00:00,overcast clouds,10.93,10.01,0.80,74
4,2023-04-02 09:00:00,overcast clouds,15.61,14.61,0.60,53
5,2023-04-02 12:00:00,light rain,18.21,17.16,3.59,41
6,2023-04-02 15:00:00,light rain,17.51,16.44,5.85,43
7,2023-04-02 18:00:00,overcast clouds,14.09,13.20,3.69,63
8,2023-04-02 21:00:00,overcast clouds,11.84,11.04,2.61,75
9,2023-04-03 00:00:00,overcast clouds,10.58,9.70,2.38,77
10,2023-04-03 03:00:00,broken clouds,11.74,10.85,5.05,72
11,2023-04-03 06:00:00,broken clouds,11.45,10.17,4.93,58
12,2023-04-03 09:00:00,overcast clouds,12.67,11.35,5.74,52
13,2023-04-03 12:00:00,broken clouds,14.25,12.64,6.93,35
14,2023-04-03 15:00:00,clear sky,13.99,12.46,7.03,39
15,2023-04-03 18:00:00,clear sky,10.10,8.47,6.52,50
16,2023-04-03 21:00:00,clear sky,8.21,4.65,6.97,49
17,2023-04-04 00:00:00,clear sky,7.19,4.16,4.80,49
18,2023-04-04 03:00:00,clear sky,6.34,3.09,4.82,46
19,2023-04-04 06:00:00,clear sky,6.27,3.08,4.66,45
20,2023-04-04 09:00:00,clear sky,9.69,6.56,6.93,32
21,2023-04-04 12:00:00,few clouds,12.06,9.97,7.06,25
22,2023-04-04 15:00:00,few clouds,11.30,9.30,6.81,31
23,2023-04-04 18:00:00,clear sky,8.30,5.86,4.10,45
24,2023-04-04 21:00:00,clear sky,7.35,4.80,3.90,51
25,2023-04-05 00:00:00,clear sky,6.64,3.64,4.45,55
26,2023-04-05 03:00:00,clear sky,6.00,3.40,3.46,56
27,2023-04-05 06:00:00,clear sky,5.87,3.81,2.65,58
28,2023-04-05 09:00:00,clear sky,10.72,8.81,4.63,37
29,2023-04-05 12:00:00,clear sky,13.06,11.23,4.89,31
30,2023-04-05 15:00:00,clear sky,12.41,10.49,5.47,30
31,2023-04-05 18:00:00,clear sky,8.82,6.59,3.93,38
32,2023-04-05 21:00:00,clear sky,6.50,4.83,2.31,49
33,2023-04-06 00:00:00,few clouds,5.30,3.32,2.43,56
34,2023-04-06 03:00:00,overcast clouds,5.53,2.69,3.69,59
35,2023-04-06 06:00:00,overcast clouds,6.03,3.59,3.22,58
36,2023-04-06 09:00:00,overcast clouds,11.15,9.23,6.90,35
37,2023-04-06 12:00:00,broken clouds,13.42,11.60,7.11,30
38,2023-04-06 15:00:00,broken clouds,12.51,10.70,6.84,34
39,2023-04-06 18:00:00,scattered clouds,9.04,6.35,5.09,55

push the data frame to MySQL

In [27]:
# we need sqlalchemy to connect to the database
# !pip install sqlalchemy

In [28]:
import sqlalchemy

In [29]:
#Installed the below package is necessary to run SQL alchemy
# pip install pymysql

In [39]:
# improting a placeholder for the MySQL password
from config import password
#in schema use the name of database not of DF
schema="weather_flight_pipelines"   # name of the database you want to use here
host="127.0.0.1"        # to connect to your local server
user="root"
password=config.password # your password!!!!
port=3306
connection_details = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

In [32]:
# push the dataframe to the MySQL database

#here use the name of DF you want to push
weather_df.to_sql('weather_df',         # 'iss_logs'-> table name;
              if_exists='append', # if_exists -> will create new table if doesn't exist, otherwise, 'append' - will append data to existing table;
              con=connection_details,            # con-> connection string;
              index=False)

40

In [38]:
forecast_df.to_sql('forecast_df',         # 'ilogs'-> table name;
              if_exists='append', # if_exists -> will create new table if doesn't exist, otherwise, 'append' - will append data to existing table;
              con=connection_details,            # con-> connection string;
              index=False)

40

FUNCTION WITH MULTIPLE CITIES

In [58]:
#FOR LOOP with list of cities
cities = ['Frankfurt', 'Istanbul']
API_key = config.API_key

city_weather_dict = {
        'city': [],
        'country_code': [],
        'forecast_time': [],
        'outlook': [],
        'temp': [],
        'feels_like': [],
        'wind_speed': [],
        'humidity': []
        }

for j in range(len(cities)):
    weather_req = requests.get(f"http://api.openweathermap.org/data/2.5/forecast?q={cities[j]}&appid={API_key}&units=metric")
    city_weather_json = weather_req.json()

# Alternatively like this: 
# for city in cities:
#  weather_city = requests.get(f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={api_key}&units=metric")
#  json = weather_city.json()
   

    for i in range(len(city_weather_json['list'])):
        city_weather_dict['city'].append(city_weather_json['city']['name'])
        city_weather_dict['country_code'].append(city_weather_json['city']['country'])
        city_weather_dict['forecast_time'].append(city_weather_json['list'][i]['dt_txt'])
        city_weather_dict['outlook'].append(city_weather_json['list'][i]['weather'][0]['description'])
        city_weather_dict['temp'].append(city_weather_json['list'][i]['main']['temp'])
        city_weather_dict['feels_like'].append(city_weather_json['list'][i]['main']['feels_like'])
        city_weather_dict['wind_speed'].append(city_weather_json['list'][i]['wind']['speed'])
        city_weather_dict['humidity'].append(city_weather_json['list'][i]['main']['humidity'])
    

city_weather_df = pd.DataFrame(city_weather_dict)

In [59]:
city_weather_df.sample(10)

,city,country_code,forecast_time,outlook,temp,feels_like,wind_speed,humidity
69,Istanbul,TR,2023-04-07 09:00:00,broken clouds,11.59,10.45,2.38,63
11,Frankfurt am Main,DE,2023-04-05 03:00:00,clear sky,0.56,-1.02,1.44,63
66,Istanbul,TR,2023-04-07 00:00:00,overcast clouds,8.74,6.98,3.03,80
71,Istanbul,TR,2023-04-07 15:00:00,scattered clouds,10.74,9.65,6.27,68
54,Istanbul,TR,2023-04-05 12:00:00,overcast clouds,7.59,4.72,4.67,80
68,Istanbul,TR,2023-04-07 06:00:00,overcast clouds,9.39,7.60,3.32,73
75,Istanbul,TR,2023-04-08 03:00:00,few clouds,7.26,4.89,3.54,91
30,Frankfurt am Main,DE,2023-04-07 12:00:00,overcast clouds,12.32,10.73,0.47,43
19,Frankfurt am Main,DE,2023-04-06 03:00:00,clear sky,2.46,2.46,1.23,66
44,Istanbul,TR,2023-04-04 06:00:00,light rain,11.47,10.84,2.68,83

In [60]:
# convert forecast_time to datetime
city_weather_df['forecast_time']  = pd.to_datetime(city_weather_df['forecast_time'])

In [61]:
city_weather_df

,city,country_code,forecast_time,outlook,temp,feels_like,wind_speed,humidity
0,Frankfurt am Main,DE,2023-04-03 18:00:00,clear sky,7.13,4.36,4.23,47
1,Frankfurt am Main,DE,2023-04-03 21:00:00,clear sky,4.68,1.75,3.54,53
2,Frankfurt am Main,DE,2023-04-04 00:00:00,clear sky,1.46,-1.39,2.60,63
3,Frankfurt am Main,DE,2023-04-04 03:00:00,clear sky,0.50,-2.33,2.40,68
4,Frankfurt am Main,DE,2023-04-04 06:00:00,few clouds,0.82,-1.71,2.18,66
...,...,...,...,...,...,...,...,...
75,Istanbul,TR,2023-04-08 03:00:00,few clouds,7.26,4.89,3.54,91
76,Istanbul,TR,2023-04-08 06:00:00,few clouds,9.08,6.64,4.52,78
77,Istanbul,TR,2023-04-08 09:00:00,broken clouds,11.59,10.48,4.55,64
78,Istanbul,TR,2023-04-08 12:00:00,broken clouds,11.51,10.39,6.05,64
79,Istanbul,TR,2023-04-08 15:00:00,overcast clouds,10.33,9.25,6.50,70

In [62]:
city_weather_df['city'].unique()

array(['Frankfurt am Main', 'Istanbul'], dtype=object)

In [71]:
#turning for loop into a function 
def get_weather_data(cities):

    API_key = config.API_key

    city_weather_dict = {
            'city': [],
            'country_code': [],
            'forecast_time': [],
            'outlook': [],
            'temp': [],
            'feels_like': [],
            'wind_speed': [],
            'humidity': []
            }

    for j in range(len(cities)):
        weather_req = requests.get(f"http://api.openweathermap.org/data/2.5/forecast?q={cities[j]}&appid={API_key}&units=metric")
        city_weather_json = weather_req.json()

    # Alternatively like this: 
    # for city in cities:
    #  weather_city = requests.get(f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={api_key}&units=metric")
    #  json = weather_city.json()
    

        for i in range(len(city_weather_json['list'])):
            city_weather_dict['city'].append(city_weather_json['city']['name'])
            city_weather_dict['country_code'].append(city_weather_json['city']['country'])
            city_weather_dict['forecast_time'].append(city_weather_json['list'][i]['dt_txt'])
            city_weather_dict['outlook'].append(city_weather_json['list'][i]['weather'][0]['description'])
            city_weather_dict['temp'].append(city_weather_json['list'][i]['main']['temp'])
            city_weather_dict['feels_like'].append(city_weather_json['list'][i]['main']['feels_like'])
            city_weather_dict['wind_speed'].append(city_weather_json['list'][i]['wind']['speed'])
            city_weather_dict['humidity'].append(city_weather_json['list'][i]['main']['humidity'])
        

    city_weather_df = pd.DataFrame(city_weather_dict)
    return city_weather_df

In [72]:
get_weather_data(['Bishkek', 'Florence', 'Tuebingen']).sample(10)

,city,country_code,forecast_time,outlook,temp,feels_like,wind_speed,humidity
60,Florence,IT,2023-04-06 06:00:00,clear sky,5.02,3.93,1.53,59
76,Florence,IT,2023-04-08 06:00:00,overcast clouds,9.05,8.72,1.36,64
89,Tübingen,DE,2023-04-04 21:00:00,overcast clouds,0.95,-0.63,1.47,74
87,Tübingen,DE,2023-04-04 15:00:00,broken clouds,7.36,4.42,4.69,44
88,Tübingen,DE,2023-04-04 18:00:00,broken clouds,3.02,0.66,2.39,66
103,Tübingen,DE,2023-04-06 15:00:00,broken clouds,11.51,9.81,0.51,42
110,Tübingen,DE,2023-04-07 12:00:00,overcast clouds,10.50,9.02,1.27,54
51,Florence,IT,2023-04-05 03:00:00,clear sky,5.95,2.64,4.75,46
74,Florence,IT,2023-04-08 00:00:00,overcast clouds,9.66,9.66,0.08,69
11,Bishkek,KG,2023-04-05 03:00:00,overcast clouds,12.39,10.94,0.60,48

create cities_df

In [84]:
#importing library for generating unique id. Not using this option for now. Commented out other related lines.
# import uuid

#FOR LOOP with list of cities
cities = ['Frankfurt', 'Istanbul']
API_key = config.API_key

city_dict = {
        'city': [],
        'country_code': [],
        'population': [],
        'latitude': [],
        'longitude': [],
        'timezone': []
        # 'city_id': []
        }

for j in range(len(cities)):
    weather_req = requests.get(f"http://api.openweathermap.org/data/2.5/forecast?q={cities[j]}&appid={API_key}&units=metric")
    city_json = weather_req.json()
    city_dict['city'].append(city_json['city']['name'])
    city_dict['country_code'].append(city_json['city']['country'])
    city_dict['population'].append(city_json['city']['population'])
    city_dict['latitude'].append(city_json['city']['coord']['lat'])
    city_dict['longitude'].append(city_json['city']['coord']['lon'])
    city_dict['timezone'].append(city_json['city']['timezone'])
    # city_dict['city_id'].append(str(uuid.uuid4()))


    

city_df = pd.DataFrame(city_dict)

In [90]:
city_df

                city country_code  population  latitude  longitude  timezone
0  Frankfurt am Main           DE      650000   50.1167     8.6833      7200
1           Istanbul           TR    11581707   41.0351    28.9833     10800

In [87]:
#importing library for generating unique id. Not using this option for now. Commented out other related lines.
# import uuid

#FUNCTION with list of cities
def get_city_data(cities):
    API_key = config.API_key

    city_dict = {
            'city': [],
            'country_code': [],
            'population': [],
            'latitude': [],
            'longitude': [],
            'timezone': []
            # 'city_id': []
            }

    for j in range(len(cities)):
        weather_req = requests.get(f"http://api.openweathermap.org/data/2.5/forecast?q={cities[j]}&appid={API_key}&units=metric")
        city_json = weather_req.json()
        city_dict['city'].append(city_json['city']['name'])
        city_dict['country_code'].append(city_json['city']['country'])
        city_dict['population'].append(city_json['city']['population'])
        city_dict['latitude'].append(city_json['city']['coord']['lat'])
        city_dict['longitude'].append(city_json['city']['coord']['lon'])
        city_dict['timezone'].append(city_json['city']['timezone'])
        # city_dict['city_id'].append(str(uuid.uuid4()))

        

    city_df = pd.DataFrame(city_dict)
    return city_df

In [88]:
cities = ['Bishkek', 'Florence', 'Tuebingen']
get_city_data(cities)

       city country_code  population  latitude  longitude  timezone
0   Bishkek           KG      900000   42.8700    74.5900     21600
1  Florence           IT      371517   43.7667    11.2500      7200
2  Tübingen           DE       15000   48.5227     9.0522      7200

In [91]:
city_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          2 non-null      object
 1   country_code  2 non-null      object
 2   population    2 non-null      int64
 3   latitude      2 non-null      float64
 4   longitude     2 non-null      float64
 5   timezone      2 non-null      int64
dtypes: float64(2), int64(2), object(2)
memory usage: 224.0+ bytes

In [76]:
# explorative codes
cities_id = pd.DataFrame({'city_id': range(len(city_df['city'].unique()))})
cities_id

   city_id
0        0
1        1

In [93]:
#explorative codes
# create a new cities_df with unique cities and unique country codes and assigning them city_id starting from 0

pd.DataFrame({'city_id': range(len(city_weather_df['city'].unique())),
                          'city_name': city_weather_df['city'].unique(), 
                          'country_code': city_weather_df['country_code'].unique()
                          })
# # cities_df['city_id'] = cities_df.index
# cities_df

   city_id          city_name country_code
0        0  Frankfurt am Main           DE
1        1           Istanbul           TR

push city_df to MySQL

In [94]:
city_df.to_sql('cities',         # 'ilogs'-> table name;
              if_exists='append', # if_exists -> will create new table if doesn't exist, otherwise, 'append' - will append data to existing table;
              con=connection_details,            # con-> connection string;
              index=False)

2